[project]
name = "moodies-backend-recommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "lancedb>=0.23.0",
    "numpy>=2.3.0",
    "polars>=1.30.0",
]
